apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app1.fullname" . }}
  labels:
    {{- include "app1.labels" . | nindent 4 }}
data:
  fluent.conf: |
    <label @FLUENT_LOG>
      <match fluent.*>
        @type null
      </match>
    </label>
    {{- with .Values.extraConfig }}
      {{- . | nindent 4 }}
    {{- end }}

