apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app1.fullname" . }}
  labels:
    {{- include "app1.labels" . | nindent 4 }}
data:
  fluent.conf: |
    <label @FLUENT_LOG>
      <match fluent.*>
        @type null
      </match>
    </label>

    <source>
      @type forward
      bind 0.0.0.0
      port 24224
    </source>

    <source>
      @type syslog
      port  5140
      bind  0.0.0.0
      tag   syslog
      severity_key severity
      facility_key facility
      <parse>
        @type syslog
        parser_type string
        support_colonless_ident false
      </parse>
    </source>

    <match kernel systemd>
      @type elasticsearch
      host elasticsearch.default
      port 9200
      log_es_400_reason true
      logstash_format true
      logstash_prefix "${tag}"
      logstash_dateformat %Y%m%d
      include_tag_key true
      tag_key @log_name
      suppress_type_name true

      reconnect_on_error true
      reload_on_failure false
      reload_connections false
      request_timeout 5s

      <buffer>
        @type memory
        flush_mode interval
        flush_interval 5s
        flush_thread_count 2
        retry_type exponential_backoff
        retry_max_interval 30
        retry_timeout 1m
        overflow_action drop_oldest_chunk
        chunk_limit_size 2M
        queue_limit_length 8
        chunk_full_threshold 0.9
      </buffer>

      slow_flush_log_threshold 25.0
    </match>

    <match syslog.**>
      @type elasticsearch
      host elasticsearch.default
      port 9200
      log_es_400_reason true
      logstash_format true
      logstash_prefix syslog
      logstash_dateformat %Y%m%d
      include_tag_key true
      tag_key @log_name
      suppress_type_name true

      reconnect_on_error true
      reload_on_failure false
      reload_connections false
      request_timeout 5s

      <buffer>
        @type memory
        flush_mode interval
        flush_interval 5s
        flush_thread_count 2
        retry_type exponential_backoff
        retry_max_interval 30
        retry_timeout 1m
        overflow_action drop_oldest_chunk
        chunk_limit_size 2M
        queue_limit_length 8
        chunk_full_threshold 0.9
      </buffer>

      slow_flush_log_threshold 25.0
    </match>

    <match kubernetes.**>
      @type elasticsearch
      host elasticsearch.default
      port 9200
      log_es_400_reason true
      logstash_format true
      logstash_prefix kubernetes
      logstash_dateformat %Y%m%d
      include_tag_key true
      tag_key @log_name
      suppress_type_name true

      reconnect_on_error true
      reload_on_failure false
      reload_connections false
      request_timeout 5s

      <buffer>
        @type memory
        flush_mode interval
        flush_interval 5s
        flush_thread_count 2
        retry_type exponential_backoff
        retry_max_interval 30
        retry_timeout 1m
        overflow_action drop_oldest_chunk
        chunk_limit_size 4M
        queue_limit_length 8
        chunk_full_threshold 0.9
      </buffer>

      slow_flush_log_threshold 25.0
    </match>

    <match *.**>
      @type stdout
    </match>
