apiVersion: v1
kind: Service
metadata:
  name: {{ include "app1.fullname" . }}
  labels:
    {{- include "app1.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: 24224tcp2
      port: 24224
      protocol: TCP
      targetPort: 24224
  selector:
    {{- include "app1.selectorLabels" . | nindent 4 }}
