apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app1.fullname" . }}
  labels:
  {{- include "app1.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem
