apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app1.fullname" . }}
  labels:
    {{- include "app1.labels" . | nindent 4 }}
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0"
    elasticsearch.hosts: [ "http://elasticsearch:9200" ]
    xpack.encryptedSavedObjects.encryptionKey: VeshfapUphhikjentOofJanPefcuHur8
