apiVersion: v2
name: prometheus
description:
type: application
version: 1.0.2

dependencies:
  - name: kube-prometheus-stack
    version: 13.7.2
    repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus-blackbox-exporter
    version: 4.10.2
    repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus-snmp-exporter
    version: 0.1.2
    repository: https://prometheus-community.github.io/helm-charts
