apiVersion: v2
name: node-feature-discovery
description:
type: application
version: 2.1.1

dependencies:
  - name: node-feature-discovery
    version: 2.1.1
    repository: https://k8s-at-home.com/charts
