image:
  repository: fluent/fluentd-kubernetes-daemonset
  tag: v1.11.5-debian-elasticsearch7-1.1
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP

ingress:
  enabled: true

resources: {}

nodeSelector: {}

tolerations:
  - effect: "NoSchedule"
    key: "ups"
    operator: "Exists"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
                - amd64
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
