image:
  repository: fluent/fluentd-kubernetes-daemonset
  tag: v1.12.2-debian-elasticsearch7-1.1
  pullPolicy: IfNotPresent

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: { }
  name:

podSecurityContext: { }

securityContext: { }

service:
  type: ClusterIP

ingress:
  enabled: true

resources: { }

nodeSelector: { }

tolerations: [ ]

affinity: { }
