apiVersion: v1
kind: Service
metadata:
  name: {{ include "app1.fullname" . }}
  labels:
  {{- include "app1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      name: http
      protocol: TCP
      targetPort: http
    - port: 9116
      name: snmp
      protocol: TCP
      targetPort: snmp
  selector:
  {{- include "app1.selectorLabels" . | nindent 4 }}
