image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: 7.10.0
  pullPolicy: IfNotPresent

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: { }
  name:

podSecurityContext: { }

securityContext: { }

service:
  type: ClusterIP
  httpPort: 9200

ingress:
  enabled: true

resources: { }

nodeSelector: { }

tolerations:
  - effect: "NoSchedule"
    key: "ups"
    operator: "Exists"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
                - amd64
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
