image:
  repository: linuxserver/unifi-controller
  tag: version-6.0.36
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  httpPort: 8443
  stunPort: 3478
  ctrldiscoveryPort: 1900
  devdiscoveryPort: 10001

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  hosts:
    - host: unifi-controller.k8s1.se.home
      paths: /
  tls:
    - hosts:
        - unifi-controller.k8s1.se.home

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
