---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: deleting-pods
  namespace: {{ .Values.restart.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deleting-pods
  namespace: {{ .Values.restart.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "patch", "list", "watch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deleting-pods
  namespace: {{ .Values.restart.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deleting-pods
subjects:
  - kind: ServiceAccount
    name: deleting-pods

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: deleting-pod
  namespace: {{ .Values.restart.namespace }}
spec:
  concurrencyPolicy: Forbid
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: deleting-pods
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - 'kubectl'
                - 'delete'
                - 'pod'
                - 'homeassistant-home-assistant-0'
                - '--force'
                - '--grace-period=0'
          {{- with .Values.restart.affinity }}
          affinity:
          {{- toYaml . | nindent 12 }}
          {{- end }}
