apiVersion: v2
name: argo-cd
description:
type: application
version: 1.0.2

dependencies:
  - name: argo-cd
    version: 2.11.6
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-notifications
    version: 1.0.11
    repository: https://argoproj.github.io/argo-helm
