apiVersion: v2
name: argo-cd
description:
type: application
version: 2.14.0

dependencies:
  - name: argo-cd
    version: 2.14.0
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-notifications
    version: 1.0.14
    repository: https://argoproj.github.io/argo-helm
