image:
  repository: grafana/grafana
  tag: 7.3.1
  pullPolicy: IfNotPresent

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: { }
  name:

podSecurityContext: { }

securityContext: { }

service:
  type: ClusterIP
  httpPort: 3000

ingress:
  enabled: true
  hosts:
    - host: grafana.k8s1.se.home
      paths: /
  tls:
    - hosts:
        - grafana.k8s1.se.home

resources: { }

nodeSelector: { }

tolerations: [ ]

affinity: { }
