image:
  repository: kibana
  tag: 7.10.1
  pullPolicy: IfNotPresent


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  httpPort: 5601

ingress:
  enabled: true
  hosts:
    - host: kibana.k8s1.se.home
      paths: /

  tls:
    - hosts:
        - kibana.k8s1.se.home

resources: {}

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
                - amd64
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
            - key: ups
              operator: Exists
