image:
  repository: fluent/fluent-bit
  tag: 1.6
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

service: {}

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
