name: publish-helm-chart

on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'

permissions:
  contents: write

jobs:
  publish-helm-chart:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@b43a8719cc63fdb3aa943cc57359ab19118eab3f
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
