name: publish-helm-chart

on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'

permissions:
  contents: write

jobs:
  publish-helm-chart:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@0ad2bb377311d61ac04ad9eb6f252fb68e207260
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
